### ISSUE TITLE
Bug argent 

### ISSUE THREAD

**Issue by Blackwave78** [Nevylish/New-LegacyFuel#1]
lorsque l'on veut faire de l'essence il ne prend pas en compte l'argent sur sois il doit y avoir un bug de refresh d'argent

**Comment by JLG4ME** [comment]
Changez la ligne 115 en 133 pour cela:

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(250)

		local pumpObject, pumpDistance = FindNearestFuelPump()

		if pumpDistance < 2.5 then
			isNearPump = pumpObject

			if Config.UseESX then
				local playerData = ESX.GetPlayerData()
				for i=1, #playerData.accounts, 1 do
					if playerData.accounts[i].name == 'money' then
						currentCash = playerData.accounts[i].money
						break
					end
				end
			end
		else
			isNearPump = false

			Citizen.Wait(math.ceil(pumpDistance * 20))
		end
	end
end)

**Comment by Blackwave78** [comment]
ok merci nikel
